# Model architecture
d_model: 256
n_head: 8
n_layers: 6
d_ff: 1024
dropout: 0.1

# Training parameters
batch_size: 64
learning_rate: 1.0e-4
num_epochs: 1000
weight_decay: 1.0e-6
scheduler_type: cosine
warmup_steps: 1000
checkpoint_freq: 50
num_output_figs: 1
validation_freq: 1   # Validate every n epoch
test_freq: 1         # Test every n epochs
viz_freq: 1000       # Visualize every n epochs

# Data parameters
data_path: data_reynolds
num_workers: 1
scaler_fname: 'airfoil_scaler.pt'

# Experiment tracking
project_name: airfoil-transfer-learning
experiment_name: baseline_transformer
tags: 
  - transformer
  - baseline
  - pressure_prediction

# Wandb settings
notes: "Baseline transformer model for transfer learning of 2D to 3D airfoil pressure prediction."
